### ISSUE TITLE
Inconsistent state between current URL and actual content if XHR request fails

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-admin#1279]
## TODO (emteknetnz):
- [x] Cross repo run of behat using vendor-code-patcher e.g. asset-admin etc
  [pass] https://github.com/emteknetnz/silverstripe-installer/actions/runs/1715647443
- [ ] ~~Write a behat test - replication steps and new required step-definition in a PR comment~~
  - this does not seem possible - cookie is HttpOnly meaning you cannot delete it with JS.  Nor can log out user serverside since php has context of behat, not the silverstripe site i.e. Security::getCurrentUser() is null

## Original issue

It appears that the CMS will enter into an inconsistent mixed state if the current XHR/AJAX server request happens to return a erroneous HTTP code (i.e. the browser will point to the **new URL** for a page that failed to load while actually showing the **old content**). 

A common use case for this would be if the user's session has timed out (or is no longer valid) and the user attempts to navigate to a new page. This presents the login dialog. However, if the user logs in, the new URL is still presented while the old panel is still visible (and the CMS is now in a mixed/inconsistent state).  See below.

**Steps to reproduce:**

1. Vanilla SilverStripe installation (`framework` and `cms` 4.9.1 and `admin` 1.9.0 at time of writing)
2. Navigate to "Home"
3. Clear cookies (including your session cookie), effectively logging you out in the same way as a typical timed out session
4. Click "About Us"
5. Log back in

![silverstripe URLs and session reauthentication modal](https://user-images.githubusercontent.com/4269377/148714536-ca670e38-6168-457a-8a20-2ab7afe815c6.gif)

# Acceptance criteria
- [ ] URL state is constant after an error.
- [ ] URL state is constant after a relogin.

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1280

**Comment by patricknelson** [comment]
@maxime-rainville I'm about to submit a PR with a proposed fix for this. Should it be branched off of (and against) `1` or `1.10` since it's more of a bug fix? 🤔

**Comment by emteknetnz** [comment]
@patricknelson easiest to branch off 1.10 because it makes retargetting it to 1 later on easier.  Which branch it should target depends on the extent of PHP API changes i.e. adding a new public or protected method in PHP means it should go into 1, though if there's only a new private method then it can go into 1.10 and be released much sooner.

**Comment by patricknelson** [comment]
Ok @emteknetnz I can rebase my PR in #1280 since it's already based on `1` instead of `1.10`. Personally I'm in no rush since I'm not on SS v4 just yet, just preparing way ahead of time (noticed this during my initial testing).  Do you think I should do that or is it fine to just leave it as-is?

**Comment by emteknetnz** [comment]
Yes recommend you rebase it to 1.10

**Comment by patricknelson** [comment]
Ok updated the PR. Turns out I already had it branched off of `1.10` but accidentally issued the PR against `1` (so no need to rebase).

**Comment by GuySartorelli** [comment]
PR merged. Closing the issue.
