### ISSUE TITLE
TODO: GridField Component Improvements

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-admin#1596]
## Description
See: https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/components/GridField/GridField.js#L23-L25
- [ ] Convert to higher order component which hooks up form schema data to an API backend as a grid data source
- [ ] Replace "dumb" inner components with third party library (e.g. https://griddlegriddle.github.io)
- [ ] Replace `<div>{ i18n._t('CampaignAdmin.LOADING', 'Loading...') }</div>` with better loading indicator. [See](https://github.com/silverstripe/silverstripe-admin/blob/0f18b3d40972d421f2756b6b90b55283dfc6fea2/client/src/components/GridField/GridField.js#L137)

**Comment by GuySartorelli** [comment]
@sabina-talipova it's not clear what is meant by "dumb" inner components, and that griddle link is a 404 - can you please either clarify what the intention was or remove that point?

If that point ends up being removed then I think we can close this issue, as the other points aren't worth doing on their own IMO.

**Comment by sabina-talipova** [comment]
I assume that the idea was to replace createRow and createCells and so on, with this JS module - [Griddle](https://griddlegriddle.github.io/Griddle/)

**Comment by GuySartorelli** [comment]
I'm going to close this for now - we're not likely to spend time working on small parts of the js of gridfield.
I suspect next time we look at enhancing or improving the gridfield javascript, it will be more akin to a complete overhaul or replacement.
