### ISSUE TITLE
Create campaign from pages/assets section

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#161]
There is no indication that you need to create a campaign before adding a page to the campaign. Screenshot of when there are no campaigns available.
![image](https://user-images.githubusercontent.com/555033/28401896-024a6ef0-6d71-11e7-8874-c4ec11f3a0c7.png)

The error message if you click add when there are no campaigns is really bad also
![image](https://user-images.githubusercontent.com/555033/28402044-c8ae055c-6d71-11e7-919b-e35b018b3464.png)

## Design prototype
https://invis.io/BWD1AXOPZ#/248625949_Campaigns_-_Add_To_Campaign_-_Menu

## AC
As a user of the CMS I'm not sure that I have to create first a campaign before a page could be added to it. I would like to be able to create a campaign from pages so that I don't have to go back and create a campaign in the Campaigns section. I want to:
- Be notified if I need to first create a campaign if I don't have any campaigns created
- Be notified if the page I want to add is already in other existing campaigns
- Be able to create new campaigns from the "Add to campaign" modal
- Be able to select a campaign which my item does not already exist in so that I can add my item (pages/files) to the selected campaign
- Get a suitable success message confirming the page has been added
- There is a suitable error message (like "Please select a campaign") to let users know a campaign must be selected before the "Add" action will work (not the current message "Available campaigns is required")

## Notes

 * Consider using a GraphQL mutation for this (we should get away from form submissions)
 * The solution should be general purpose: While it's not crucial for this card, we'll want to add this to the files section without duplication (and to ModelAdmin/GridField at some point later)
 * Excludes searching for campaigns in the dropdown
 * Would be good to implement a cleaner full solution in the future which alows create action within the threedropdown field (https://github.com/silverstripe/silverstripe-admin/issues/161#issuecomment-318969298)

## Tasks

 - [x] Update form for add to campaign
 - [x] Update admin/pages section
 - [x] update admin/assets section
 - [x] Ensure form validation is functional
 - [x] Ensure create campaign form action works
 - [x] Ensure select campaign action continues to work
 - [x] Ensure form messages for each state are displayed
 - [x] Ensure success message is updated based on action 
 
## PRs

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/212
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/216
 - [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/51
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/608
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1943
 - [x] https://github.com/unclecheese/react-selectable/issues/39 
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/606#pullrequestreview-59448378
 - More to come ...
 
## WIP Branches

 - https://github.com/open-sausages/silverstripe-campaign-admin/tree/pulls/1.0/create-campaign-form
 - https://github.com/open-sausages/silverstripe-admin/tree/pulls/1.0/create-campaign-form
 - https://github.com/open-sausages/silverstripe-asset-admin/tree/pulls/1.0/create-campaign-form
- https://github.com/open-sausages/silverstripe-cms/tree/pulls/4.0/create-campaign-form

**Comment by clarkepaul** [comment]
@flamerohr if you have some time to see if you think the following is doable.
Can we add the functionality to allow user's to select items and add new campaigns within the same UI as per mockups?
![add to campaign modal](https://user-images.githubusercontent.com/555033/28763553-1c206910-7613-11e7-8a13-c26e02a25e73.png)

If a campaign is not selected, we should also update the error message to something like "Please select a campaign".

**Comment by flamerohr** [comment]
That's an interesting approach, a few steps required come to mind:
* Migrate the current `SingleSelectField` component to use `react-select` first, this will be a different implementation to the `TreeDropdownField`, but unifies the styling of both dropdown fields.
* Build some custom handling in the PHP to handle creating the Campaign on submit.
* Some kind of "Allow create if not found" flag API added to SingleSelectField.

So when the user types, the option to "create" appears and options are also filtered at the same time right?
I think this is all doable, might be a bit of work involved but not as much as the `TreeDropdownField` work that was done

**Comment by clarkepaul** [comment]
@flamerohr FYI there is an example of "create" on the React select library you referenced (look for Github example / create http://jedwatson.github.io/react-select/ )

**Comment by flamerohr** [comment]
yes, `react-select` has the feature, I'm more concerned with how much effort/hacking/refactoring may be needed to achieve this ;)

**Comment by newleeland** [comment]
Hey @flamerohr, how about if we used radio buttons, to show input fields
So if you have an existing campaign created we show:
![add to existing campaign open](https://user-images.githubusercontent.com/8085295/29257970-2a63d7a8-810a-11e7-8da1-3251243ab8e4.png)

However, if we don't have any campaigns, we just show the option to create and add to a campaign
![no campaign open](https://user-images.githubusercontent.com/8085295/29258017-76aa2482-810a-11e7-8966-0fc7c0c5bab5.png)

**Comment by flamerohr** [comment]
@newleeland that sounds like a good idea :) much more clarity than typing in a mixed select box

**Comment by newleeland** [comment]
This is how the above design would potentially work @clarkepaul @flamerohr 

*Prototype design*
https://invis.io/BWD1AXOPZ#/248625949_Campaigns_-_Add_To_Campaign_-_Menu

**Comment by clarkepaul** [comment]
FYI replacing designs at the top with updated simplified version as created on the 31st Aug.

**Comment by tractorcow** [comment]
Screenshots of current Prs:

![image](https://user-images.githubusercontent.com/936064/29902034-b9aaf57a-8e4f-11e7-8cf8-356575405cb1.png)

![image](https://user-images.githubusercontent.com/936064/29902043-c6011e9e-8e4f-11e7-8b70-31b2cce9adda.png)

![image](https://user-images.githubusercontent.com/936064/29902047-cde464cc-8e4f-11e7-89ff-80c812fb243e.png)

![image](https://user-images.githubusercontent.com/936064/29902049-d5583f08-8e4f-11e7-811c-8ac7ef5ff5d1.png)

![image](https://user-images.githubusercontent.com/936064/29902061-ec6f07ee-8e4f-11e7-9314-49adf74ada99.png)

**Comment by tractorcow** [comment]
This is now ready to review.

**Comment by newleeland** [comment]
### Item is in All Campaigns (Admin)
![image](https://user-images.githubusercontent.com/936064/29902034-b9aaf57a-8e4f-11e7-8cf8-356575405cb1.png)

### Item is in All Campaigns (Limited user)
![image](https://user-images.githubusercontent.com/936064/29902061-ec6f07ee-8e4f-11e7-9314-49adf74ada99.png)

### Admin flow when there are available campaigns
![image](https://user-images.githubusercontent.com/936064/29902043-c6011e9e-8e4f-11e7-8b70-31b2cce9adda.png)

![image](https://user-images.githubusercontent.com/936064/29902047-cde464cc-8e4f-11e7-89ff-80c812fb243e.png)

![image](https://user-images.githubusercontent.com/936064/29902049-d5583f08-8e4f-11e7-811c-8ac7ef5ff5d1.png)

**Comment by tractorcow** [comment]
Updated screenshots:

![image](https://user-images.githubusercontent.com/936064/29948039-d366db30-8f00-11e7-8cdd-aa007086ed56.png)

![image](https://user-images.githubusercontent.com/936064/29948068-07d706a6-8f01-11e7-8761-439e65bf1185.png)

![image](https://user-images.githubusercontent.com/936064/29948091-2072d096-8f01-11e7-889b-9ddc2c0f1598.png)

**Comment by tractorcow** [comment]
![image](https://user-images.githubusercontent.com/936064/29948153-6ee4a844-8f01-11e7-904f-65a316ab7ba3.png)

**Comment by tractorcow** [comment]
Updated again, but added placeholders.

![image](https://user-images.githubusercontent.com/936064/29951415-ad2ae202-8f16-11e7-978a-30cae316b1fc.png)
