### ISSUE TITLE
Insert link in TinyMCE not intuitive to select text prior to adding link

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#164]
## AC's

* If no text selected in the WYSIWYG prior to clicking one of the insert options the user is presented with a field to add link text which will be inserted back into the editor
   * If the "Link text" is then edited in the inset link form the text is updated in the editor when save is clicked
   * "Link text" works for the following options: page link, email, link to file
   * "Link text" field is a required field
* If text is selected in the WYSIWYG there is no "Link text" field 
* If an image/video is selected in the WYSIWYG editor there is no "Link text" field
* If an unknown item eg. button, OMBED is selected there is no "Link text" field
* the order of the fields is as follows
![image](https://user-images.githubusercontent.com/555033/28851144-d70d0f78-7774-11e7-96db-3c8032b5a14c.png)

## Background

To insert a link a user needs to first highlight text, this isn't as intuitive as it may seem. Admin's use the same pattern as for inserting files (placing their cursor on the page where they want the link to be placed). There is no warning that an image/text isn't selected and the user continues through the process to add the link but nothing happens when the insert button is clicked.

To avoid this happening we could:
* Disable the insert link action unless something is selected (as per SS3)
* Add another field for link text (Common on other CMS's) unless there is an image selected.

## Tasks
 - [x] Designer to specify the order of fields and label for new field
 - [x] Add "Link text" field on forms when nothing is selected (page link, file link, email link, external link)
 - [x] Conditionally hide "Link text" field based on selected content
 - [x] Make sure changes to value in the "Link text" field reflected back in selected content in the editor

## Excluded
- Specific styling of required fields (just use what is there, even if there is no indication of required fields)

## Considerations for future—progressive enhancements
- Populate the link text field with what is entered in the first field (eg page name, email address, external URL)
- Because we are hiding the "Link text" field if something is selected we have a slightly jarring experience if you initially have the field and press "Insert link" and then go to edit the same link again the field is gone. We could show the "Link text" field with what is in the editor for further editing in the modal. If it was complex data we could show the field as < Defined in editor > (eg. images, html... )

## Pull requests

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/177
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1917
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/572
