### ISSUE TITLE
Add "contains" column to campaigns overview table

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#166]
In campaign list page, as a user I would like to see:
 - How many items are in the campaign in total (Total = modified + draft + published)
 - How many changes (draft + modified) items are in the campaign
 - It should say "Empty" when the number of items is zero

The pink box indicates where these changes take place:
<img width="497" alt="pasted_image_28_08_17__6_51_pm" src="https://user-images.githubusercontent.com/555033/29762307-ffd82d7c-8c21-11e7-91a5-23030cd8b63b.png">

## Tasks
- [x] Add a column title to "Contains"
- [x] Add number of items to column details, showing "x item(s)" or "Empty" if there is no items.
- [x] Ensure the "Changes" column is a count of items which are draft and modified only (not published)

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/46
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/39

**Comment by unclecheese** [comment]
This is currently blocked by https://github.com/silverstripe/silverstripe-framework/issues/7226

**Comment by phalkunz** [comment]
@clarkepaul Actually, with this intended changes the **Contains** column will be the same as **Changes** column. =

**Comment by clarkepaul** [comment]
Based on conversations with @tractorcow and his suggestion to combine the two columns "Changes" and "Contains" (good idea) I'm suggesting we go with something like this:
![image](https://user-images.githubusercontent.com/555033/29759492-67d0f632-8c10-11e7-8602-d4ada74c0265.png)

**Comment by unclecheese** [comment]
I dig that solution. Nice one.

**Comment by tractorcow** [comment]
I'm going to adjust this change so that `getDetails` returns the new format, rather than add / remove columns. Will update tomorrow. :)

**Comment by clarkepaul** [comment]
I updated the image at the top based on the conversation but the tasks still need updating. Seems we might need to break up active campaigns from published campaigns fairly soon as you'd more likely want to know when it was created and who created the campaign.

**Comment by clarkepaul** [comment]
@tractorcow @unclecheese Once a campaign is published and items are changed out the campaign is there any point stating how many changes the campaign has, might be helpful info but could also be misleading?

**Comment by tractorcow** [comment]
@clarkepaul the changes will still represent what was changed, so it'll remain valid.
