### ISSUE TITLE
4.x performance regressions

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#199]
`admin/pages` takes 4x as long to load in SS4 compared to SS3. That's on a comparable default database, with the same hardware. The numbers are roughly equivalent between PHP 5.6 and PHP 7.1. Both configurations are fairly default, and have Zend Opcache enabled. Switching between dev and live mode doesn't seem to make a difference.

There doesn't seem to be a clear culprit, although `ClassInfo::class_name()` takes an insanely long time for 15k calls (still only 5% of the total request though). I've observed that there's a lot more overall method calls: In 3.x, `Config::inst` has the highest call count with 2004, in 4.x there's at least 20 methods with higher call counts, all the way up to 15k. What's going on here?

![image](https://user-images.githubusercontent.com/111025/29445008-1a0da970-8438-11e7-96bc-439654f0de5f.png)

![image](https://user-images.githubusercontent.com/111025/29445017-28694ab0-8438-11e7-99a1-6ed259e5c94c.png)

## Tasks:

 - [x] Investigate and diagnose major issues
 - [x] Restore deferred CMS loading
 - [x] Prevent graphql loading on every request
 - [x] Minimise excess config API usage
 - [ ] Minimise excessive config.update api calls
 - [ ] Minimise unnecessary SSViewer.render template calls
 - [ ] Speed up i18n
 - [ ] Speed up extension construction
 - [ ] Reduce unnecessary template variable evaluation
 - [ ] speed up class / model schema lookup
 - [ ] Speed up classloading

## Related issues:

 - [x] https://github.com/silverstripe/silverstripe-framework/issues/7378
 - [x] https://github.com/silverstripe/silverstripe-admin/issues/264
 - [x] https://github.com/silverstripe/silverstripe-config/issues/20
 - [x] https://github.com/silverstripe/silverstripe-framework/issues/7381
 - [x] https://github.com/silverstripe/silverstripe-framework/issues/7382
 - [x] https://github.com/silverstripe/silverstripe-framework/issues/7383
 - [ ] https://github.com/silverstripe/silverstripe-framework/issues/7384
 - [x] https://github.com/silverstripe/silverstripe-framework/issues/7385

## PRs:

- [x] https://github.com/silverstripe/silverstripe-cms/pull/1927
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7292
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7293
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7386
- [x] https://github.com/silverstripe/silverstripe-config/pull/21
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1973

Note: More PRs to come.

**Comment by kinglozzer** [comment]
@chillu In SS3, the tree view is built by a subsequent AJAX request but in SS4 it’s built as part of the initial request to `admin/pages`, I think that could explain some of the difference? Not sure how much it would account for

**Comment by chillu** [comment]
Thanks, that's a good data point. Do you know why that decision was made? When I've built the SS3 UI, I've specifically lazy loaded the tree for that reason. The CMS UI is useful without the tree if your primary goal is editing a page, so lazy loading has minimal UX impact. And even if you want to interact with the tree itself, giving the user fast feedback with a loading indicator is IMHO preferrable to a longer initial load. /cc @tractorcow

**Comment by tractorcow** [comment]
The request was removed from the ajax because the overhead of the additional request was greater than that of including it in the same request.

> The CMS UI is useful without the tree if your primary goal is editing a page

You can't select the page to edit without the tree so no it's not.

**Comment by tractorcow** [comment]
I'll do some investigation and get back with some suggestions.

**Comment by chillu** [comment]
> The request was removed from the ajax because the overhead of the additional request was greater than that of including it in the same request.

Overhead on what? A subset of users will achieve their goal faster (edit page, navigate to a different section after login), and all users will perceive a faster CMS load time. The 3.x PJAX solution puts more strain on the webserver, but that's parallelised requests which standard webservers can handle without degrading performance elsewhere.

> You can't select the page to edit without the tree so no it's not.

Many "edit page" views will be from direct links, e.g. in campaign admin, a "related pages" report, a bookmark by a CMS author, a workflow email. All of those requests now take 4x as long.

**Comment by tractorcow** [comment]
How about we restore the ajax request for the sub-tree, but only in page-edit view (not in landing page view). That would still allow edit form to load faster, but without requiring multiple ajax requests in cases where the UI isn't usable until all have completed.

**Comment by chillu** [comment]
The CMS loads the "Pages" section by default after login. This might not be the section you want to reach though (e.g. maybe you're a sysadmin that wants to add a user, or publish a campaign). In all of those cases, the initial CMS request takes 4x as long until you can switch to the section you want. 

Also, what if you opted to manage your website through the list view rather than the tree? Do you still need to wait for the tree to load every time? While this might not be a perfect UX just yet, I want this to be a viable method for authors going forward. Many sites don't benefit from the tree, either because their IA is too simple or too complex for a tree.

I don't understand what the issue is with multiple AJAX requests. Progressive loading of UIs is pretty common, and will only become more common as we more to GraphQL powered UIs. The initial load needs to be as fast as possible IMHO. /cc @clarkepaul

**Comment by tractorcow** [comment]
Ok, point taken. I will look at re-introducing progressive loading of these sections.

**Comment by clarkepaul** [comment]
I think the default view once logging in should either be a dashboard of sorts, or the actual site in preview mode. Users should be comfortable navigating their site through their site's navigation and they'll have access to the other admin areas if they wish. The only downside to the site loading this is that if their site is not performant then they have a similar issue about waiting for things to load.

**Comment by tractorcow** [comment]
I've restored deferred loading of the tree with https://github.com/silverstripe/silverstripe-cms/pull/1927, but there is yet work to do.

**Comment by tractorcow** [comment]
Some benchmarking of admin/pages shows a LOT of additional API calls in 4.x over 3.x.

3.x: https://gist.github.com/tractorcow/3692eb637ecb184191e84ab0d0a5d461
4.x: https://gist.github.com/tractorcow/7f0e759800029fdb84a4dab7e7c29204

**Comment by tractorcow** [comment]
I've discovered another cause of performance regressions. In 4.x we construct DBField instances at about 8 times the rate. This is caused by the fact that we apply default_cast to every variable template, where in 3.x we would often leave them un-escaped.

**Comment by tractorcow** [comment]
@sminnee has also just added https://github.com/silverstripe/silverstripe-framework/pull/7293

**Comment by kinglozzer** [comment]
Semi-related (though admittedly more beneficial to non-CMS performance) - `Security::database_is_ready()` still has a “hack” which triggers autoloading of a few member/permission related classes. It may be worth looking into whether this can be removed: https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-beta2/src/Security/Security.php#L1228-L1230

**Comment by sminnee** [comment]
Related to @kinglozzer's comment: https://github.com/silverstripe/silverstripe-framework/issues/7296

**Comment by chillu** [comment]
Good work everyone! Both the `admin/pages` and `admin/pages/edit/show/<id>` page loads (without XHR) take about twice as long as in 3.x - so we've gotten better, but the system is still noticeably slower overall. The homepage in the default theme also takes 1.5 to 2x as long to load, which isn't good - because that'll be felt by every website out there.

Assuming the low hanging fruit are picked, does anybody have suggestions on next steps?

**Comment by kinglozzer** [comment]
I’m away from my desk this week, but I seem to remember there being some overlap between `ExtensionMiddleware` and `InheritanceMiddleware` that I meant to look at. `InheritanceMiddleware` triggers config lookups (via `ExtensionMiddleware::getClassConfig()`)  up the class hierarchy for classes that may have already been “resolved”.

**Comment by tractorcow** [comment]
@kinglozzer well, one of those middlewares applies extension vertically (inheritance) and the other horizontally (extension), but they are the same principals. However, these calls are cached, so as long as you aren't modifying your config on every request you shouldn't see any performance hits due to these middlewares.

**Comment by tractorcow** [comment]
I have been using https://blackfire.io/ for profiling and found it extremely useful and easy to use. I suggest anyone wishing to repeat this testing on their own install check it out. I'm using the free profile, which seems sufficient for my needs.

**Comment by chillu** [comment]
Damian has suggested a lot of incremental fixes, some of which we'll plan to tackle before 4.0 stable. 

I’ve just done some perf tests with 3 vs. 4 with and without xdebug enabled, and it looks like xdebug affects 4.x a lot more. Meaning with xdebug disabled, the stats look a lot more similar (~30% slower): https://gist.github.com/chillu/9e30ecef0f0b217c8ef7f379babdecd4

Manually averaged stats on CMS (more representative of a normal workload):
Without xdebug: admin/pages is ~80ms on 3.x, and ~100ms on 4.x
With xdebug: admin/pages is ~180ms on 3.x, and ~450ms on 4.x

Unless I'm missing something here, this decreases the priority of this issue. Note that it's on PHP 7.1 with a fast SSD on a locally hosted DB, so different versions and system configurations might expose other bottlenecks.

**Comment by sminnee** [comment]
The performance blow-out with xdebug is a little strange, and worthy of a bit more investigation, but medium priority.

I still think that a 25%-30% slow-down would be worthy of more attention. However, I would say that slow-down of front-end code is more critical to address than slow-down of the CMS, as it has a direct impact on site load capacity.

Perhaps some load testing on a reasonably complex site's homepage or similar would be worthwhile?

**Comment by chillu** [comment]
Removing from milestone, since we've actioned some high value stuff already, and there's a bit more in the beta4 milestone. @tractorcow Do you feel like the unfinished tasks in the description are covered by specific pull requests already? If some aren't, can we make more specific investigation issues please? This issue has the potential to stay open for a long time otherwise :D

**Comment by sminnee** [comment]
@chillu either "Serious CMS performance regressions" no longer applies or this should be in the milestone. ;-)

 * What problem is still present that necessitates this ticket being open? (a.k.a "how big are the performance regressions that still remain?") 
 * What would it take to close this ticket?

I'm a little worried that this ticket will hang around like 💩 on a shoe, and I don't think that's helpful for backlog maintenance.

If there's something more that we expect to do in 4.x, let's quantify what that is.

**Comment by chillu** [comment]
I've changed the title to "Performance regressions". But as I've said in my last comment, I'm happy to close this ticket and have more focused discussions elsewhere, just waiting for Damian's feedback :)

Damian has already done some of the recommendations:

https://github.com/silverstripe/silverstripe-admin/issues/264
https://github.com/silverstripe/silverstripe-framework/issues/7383
https://github.com/silverstripe/silverstripe-framework/issues/7385

There's currently two further perf related issues planned for beta4:

https://github.com/silverstripe/silverstripe-framework/issues/7382
https://github.com/silverstripe/silverstripe-framework/issues/7381

**Comment by tractorcow** [comment]
Pretty much all of the issues we have planned on 4.x have been implemented. Closing this placeholder story for now.
