### ISSUE TITLE
Update ApolloClient from 0.5 to 2.x

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#423]
# Overview

Our version of ApolloClient is 1.5 years old. While its still performing it's current duties well, a version that old won't be a good base to build further features on.

# Tasks

 * [ ] ~~Switch to `apollo-boost` package~~
 * [ ] Rewrite query manager to links

# Notes

 * Already have a fetch polyfill (isomorphic-fetch)
 * Need to review changelog for 0.5 to 1.0 breaking changes

# Related

 * [Apollo: Migrating from 1.0](https://www.apollographql.com/docs/react/2.0-migration.html)
 * [CHANGELOG](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/CHANGELOG.md)
 * [UPGRADE.md](https://github.com/apollographql/apollo-client/blob/master/Upgrade.md)
 * [Apollo Client 2.0 Blog Post](https://dev-blog.apollodata.com/apollo-client-2-0-beyond-graphql-apis-888807b53afe)
 * [Customise GraphQL queries and mutations](https://github.com/silverstripe/silverstripe-graphql/issues/13)

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/514
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/780
- [ ] https://github.com/silverstripe/silverstripe-graphql/pull/154

**Comment by lukereative** [comment]
In order to upgrade to Apollo 2.x we need to use the new cache system called [IntrospectionFragmentMatcher](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher) which requires providing JSON to Apollo that lists all the fragments in the GraphQL schema.

## Proposed solutions

1. Generate a JSON file on `flush` and store it in the `ASSETS_DIR`, since that is the only guaranteed writable directory, this file can then be read when creating the Apollo client while loading the CMS.
   - The main benefit of this is avoiding adding a dynamic request upon loading the CMS (which in testing added ~500ms to initial CMS load)
   - The downside being that this adds another step for developers making changes to PHP GraphQL interfaces, if their changes are to YAML then they would need to `flush` anyway.
2. Add a dynamic request to the building of the Apollo client, which happens upon CMS load. The pros and cons are opposite to the previous solution:
   - The main benefit of this is not having to `flush` when making changes to PHP GraphQL interfaces.
   - The downside is adding the extra dynamic request which adds ~500ms to CMS load, which is highly undesirable.
   - This solution could be improved with greater server-side caching of GraphQL, which could bring request times to an acceptable level, but this would take a considerable amount of work which should be tackled separate to this issue

**Comment by unclecheese** [comment]
Schema caching work is here: https://github.com/silverstripe/silverstripe-graphql/pull/154

Allows for both dynamic requests and static filesystem caching.

**Comment by unclecheese** [comment]
Have created new ticket for taking advantage of Apollo 2 work once merged: https://github.com/silverstripe/silverstripe-asset-admin/issues/781

**Comment by maxime-rainville** [comment]
Oups ... didn't mean to close this.
