### ISSUE TITLE
Epic: React GridField

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-admin#463]
Placeholder for the list of stories to be written for GridField in react.

GridField core

  - [ ] Form-schema support for GridField components https://github.com/silverstripe/silverstripe-admin/issues/386
 - [ ] Minimal GridField HOC
 - [ ] Minimal GridField scaffolded in react / formschema
 - [ ] GraphQL backed data source for GridField
 - [ ] GridField detail / edit form for react admin
 - [ ] GridField gnostic react admin breadcrumbs
 - [ ] Read-only gridfield https://github.com/silverstripe/silverstripe-framework/issues/3357

GridField components: 
 
 - [ ] GridField delete component
 - [ ] GridField publish component
 - [ ] GridField search component
 - [ ] GridField pagination component
 - [ ] GridField order component (may be a part of core gridfield and not component maybe?)
 
Note: You'll need the zenhub.com browser extension to see the storycards in this epic

## Related

 * [RFC: New  React based replacement for GridFieldDetailForm](https://github.com/silverstripe/silverstripe-admin/issues/590)
 * [RFC: React/GraphQL GridField](https://github.com/silverstripe/silverstripe-admin/issues/556)
 * [Passing data into a React GridField](https://github.com/silverstripe/silverstripe-admin/issues/537)
 * [Extensibility for React Gridfield](https://github.com/silverstripe/silverstripe-admin/issues/386)

**Comment by chillu** [comment]
A few design goals from my perspective:

 * GridField relies on GraphQL for data. This means every DataObject managed through the CMS needs to be exposed via GraphQL. 
 * Simpler data transformation should default to injected JavaScript logic (e.g. showing linked breadcrumbs in a cell)
 * Complex data transformation should use GraphQL resolvers (e.g. count number of published child pages)
 * GridField PHP code produces a declarative form schema, and defers any data handling to JavaScript.
 * GridField presentation can be customised through declarative components
 * Writing custom GridField components requires JavaScript compilation
 * Most GridField customisations (e.g. field casting) do not require JavaScript compilation
 * GridField data handling can be customised through injected GraphQL query modifications and injected Redux state modifications

Assumptions:

 * It is not feasible for a React GridField PHP API to be fully backwards compatible with the current GridField, but we'll try to keep upgrade pains minimal
 * GraphQL endpoints are fast enough to improve the overall CMS UX, even when managing 50+ types (see [Cache GraphQL Schema](https://github.com/silverstripe/silverstripe-graphql/issues/130) issue)
 * A React GridField will completely replace the current PHP GridField, there is no "compatibility mode" once we switch to fully React-powered forms

Current data handling requirements in GridField:

 * Filter by `DataObject` fields
 * Manage relationship (has_many, many_many)
 * Select fields on joined tables
 * View fields from custom `DataObject` getters
 * Aggregate fields on joined tables
 * Filter by fields on joined tables
 * Filter by callback
 * Compose filters as nested conditionals
 * View custom `SS_List` collection of `DataObject`
 * View custom `SS_List` collection of `ViewableData`
 * Enforce permissions

I think solving the `DataList vs. GraphQL vs. GridField` architecture is actually more important than how we represent components in the form schema, and what APIs we provide to build and customise these (lots of this has already been solved by the likes of Griddle).

**Comment by chillu** [comment]
Damian has started a PoC: https://github.com/tractorcow/react-gridfield

**Comment by madmatt** [comment]
Has there been work done looking at existing React data table implementations? There seems to be quite a few out there already, some with tons of functionality...

They might be challenging to implement in the CMS though...

**Comment by sunnysideup** [comment]
Please make sure to also make it look good so that people will actually feel great about using it.

**Comment by patricknelson** [comment]
Documenting here, for search purposes (for those without Zenhub extension*), that this also impacts SilverStripe's use of `entwine`, which is on the roadmap for _removal_ per https://github.com/silverstripe/silverstripe-admin/issues/411#issuecomment-563716594.  If another ticket is ever created on Github to track the removal of `entwine` at all, I'd love to know (please note that in this thread)!

_* Note: I didn't install the extension considering the privacy concerns, so I'm not sure what details are contained therein._

**Comment by ScopeyNZ** [comment]
Just want to note also that although `entwine` is set for removal, you are still welcome to create modules that include and use `entwine`. Using `entwine` on the CMS interface after its removal will be very hacky though - the interface should be entirely React driven.

**Comment by maxime-rainville** [comment]
Yeah. That's not happening anytime soon.
