### ISSUE TITLE
Implement a TreeMultiSelectField in React

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#53]
## Acceptance Criteria

 * I can choose multiple items from hierarchical data
 * I can search for items in the same way as with single select TreeDropdown (see https://github.com/silverstripe/silverstripe-framework/issues/6842)
 * I can remove single items for multi selects
 * Selected values show their labels even when the element is not available in the list yet (due to lazy loading)
 * The field complies with WCAG accessibility guidelines
 * The field can handle at least five selected items without breaking the layout
 * The field presents selection efficiently in readonly/disabled views

## Tasks
- [x] Multiple values can be selected
- [x] Cater for "unchanged" empty value when no option is selected in TreeMultiselectField
- [x] Show selected values which are not found in the tree
- [x] Ensure single select still works
- [x] Ensure readonly/disabled view works with correct titles
- [x] unit tests

## Nice to haves
- [ ] simplify the logic around reducers and components
- [x] The field efficiently displays long tiles as selected items (and provides context on nested items)

## Notes

 * This should be a specialisation of the existing `<TreeDropdownField>` component, ideally with minimal code duplication
 * The field UX isn't really designed for selecting lots of items (e.g. for "related documents", a relational GridField is the better choice).

## Designs
Looking for feedback on these (WIP) https://projects.invisionapp.com/boards/D3X68PS46K28/

## Related

 * [Use react-select for react-based dropdowns (SingleSelectField and MultiSelectField)](https://github.com/silverstripe/silverstripe-admin/issues/52)
 * [TreeDropdownField - React Search Feature](https://github.com/silverstripe/silverstripe-framework/issues/6842)
 * [Use React-based TreeDropdownField in non-React sections](https://github.com/silverstripe/silverstripe-admin/issues/142)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7206
- [x] https://github.com/silverstripe/silverstripe-admin/pull/170
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/564
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1910

**Comment by chillu** [comment]
Damian brought up a good point: We might not not this field at all.

- MultiSelectField can already be used for "breadcrumb flattened" shallow trees like a groups hierarchy
- Common uses like "related pages" typically rely on GridField with a single TreeDropdownField
- We don't use TreeMultiSelectField in core

Given this, I'm removing the 4.0 milestone. Keeping the ticket around a bit until there's more clarity if we can remove this use case completely.

**Comment by chillu** [comment]
@clarkepaul Can you please give this some design love? Fairly high priority, since there's dependant cards.

**Comment by chillu** [comment]
@clarkepaul Are you considering multi-select for large trees as well? This might need a multi-stage process, where you search, add one or more items from the results, then do another search and add more items.

**Comment by clarkepaul** [comment]
This needs a design review before dev starts ie there is no code to peer review.

**Comment by flamerohr** [comment]
@clarkepaul The designs look good :) and inline with what `react-select` does so it shouldn't be too different aesthetic-wise
one question - should the border of the selected items be light grey instead? as it'll continue being light blue after users have tabbed to another field

**Comment by chillu** [comment]
@clarkepaul Designs look great! A few notes:

 * Should we include paths in the selected items? You could end up with two items having the same label and looking like duplicates, but in fact they're in different paths. We'll likely need ellipsis long titles as well. It does start to stretch this UI paradigm (as opposed to a more structured list-based selection)
 * How do we deal with long titles in selections?
 * It's a bit weird that the "parent" option is indented more than it's children ("Option 4" vs. "Option 4.1"), but I don't have a good solution for this either.
 * Does a click on a selected item in the list unselect the item, or close the panel?

**Comment by clarkepaul** [comment]
> Should we include paths in the selected items?
I think for now it's okay to not show the path for these, for the edge cases where there are items with the same name users will need to keep note of where they are at. If we add breadcrumbs the UI will bloat easily and become unusable to the majority of people using the tool. I also think we can leave names as full names and not truncate them (as per library we are using which works well enough)

> How do you visually communicate that you can still search by focusing on the main form element
On focus, there is a blinking cursor to indicate you can type.

> How do we deal with long titles in selections?
They wrap onto the next line.

> It's a bit weird that the "parent" option is indented more than its children
Agree it's weird but felt like it communicates the way back better as it's the opposite direction as the arrow going deeper. The alternative is to centre the parent "< Parent" in that area. Happy to hear thoughts as to which is preferred. Other option...
<img width="161" alt="pasted_image_17_07_17__10_19_pm" src="https://user-images.githubusercontent.com/555033/28264304-6d16216e-6b3e-11e7-9af1-e3e9e2af31b6.png">

> Does a click on a selected item in the list unselect the item, or close the panel?
I don't think the click would do anything (ie. it is not selectable), nor would it close the panel.

> Backspace on my keyboard after focusing in the field deletes item?
Yes that's built in

> How do you visually communicate that you can still search by focusing on the main form element, even when existing selected items are in the field?
There is a flashing cursor line when the field is in focus to indicate you can still type, this should be sufficient as space is at a premium.

**Comment by clarkepaul** [comment]
@flamerohr do you mean the border for these selected items?
![image](https://user-images.githubusercontent.com/555033/28264737-7390619c-6b40-11e7-81ae-3bf6e4bcf6d1.png)
I was thinking to keep them with the selected blue border (similar to when you have files selected in the Files area) but will take your lead if that doesn't work in reality. Perhaps they are only blue when the field is focused or opened?

**Comment by flamerohr** [comment]
Cheers, this answers all the questions, I think we could start implementing this after tasking it up :) moving it back to "Next"

**Comment by tractorcow** [comment]
Reviewing now.
