### ISSUE TITLE
Inline edit/remove of links in HTML editor

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#66]
## Acceptance Criteria

 * I can open an edit dialog when focusing on a link without going through the "insert" button in the toolbar
 * The dialog opens correctly based on the link type (page, url, anchor, file, email)
 * I can remove a link from selected text without opening a dialog
 * It is clear to authors that the actions remove the link, not the linked text itself 
 * The "unlink" button in the editor toolbar is removed, since it's duplicate functionality and clutter

## Notes

 * Design: https://projects.invisionapp.com/share/BGAYOTRFY#/screens/233190188
 * The 3.x UX forces authors to choose "insert link" in the TinyMCE menu in order to edit said link, which is counterintuitive
 * Follow on task from https://github.com/silverstripe/silverstripe-admin/issues/65
 * Ideally we have a label for the link in the overlay as a preview, but that's going to be hard because it we link shortcodes to database IDs for files and page links. So we'd need to load their titles/urls via XHR, which is out of scope for now
 * Check Wordpress implementation, we might be able to reuse the TinyMCE implementation

## Tasks

- [x] Create inline toolbar with 2 buttons – edit and unlink
- [x] Show the toolbar when a link node is focused in
- [x] Display the right link dialog box when clicking Edit button
- [x] Toolbar positioning
- [x] Styling

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6936
- [x] https://github.com/silverstripe/silverstripe-admin/pull/145
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1893
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/545

## Related

 * [New UX insert link dialog - internal URLs](https://github.com/silverstripe/silverstripe-framework/issues/6740)
 * [New UX insert link dialog - Insert anchors](https://github.com/silverstripe/silverstripe-admin/issues/65)
